version: "2"

services:
  mysql:
    image: mariadb:latest
    container_name: mysql
    environment:
      MYSQL_DATABASE: aftas_v1
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    volumes:
      - data:/var/lib/mysql
    ports:
      - "3306:3306"

  frontend:
    image: aftas_frontend
    container_name: aftas_fe
    build:
      context: .
    ports:
      - "4200:4200"
    depends_on:
      - backend

  backend:
    image: aftas_backend
    build:
      context: .
    container_name: aftas_be
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/aftas_v1?useSSL=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD:""
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"

volumes:
  data:
    driver: local
