version: "2"

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -hlocalhost -uroot"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: aftas_v1
      MYSQL_USER: root
      MYSQL_PASSWORD: ""
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "3306:3306"

  frontend:
    image: aftas_frontend
    container_name: aftas_fe
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - backend

  backend:
    image: aftas_backend
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aftas_be
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/aftas_v1?useSSL=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD:""
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8081:8081"

volumes:
  mysql:
    driver: local
